version: 2

models:
  - name: stg_customer
    description: "Importing customer table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: id
        tests:
          - not_null 
          - unique   
   
  - name: stg_employee_privileges
    description: "Importing employee privileges table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: EMPLOYEE_ID
        tests:
          - not_null 
          - unique   
  - name: stg_employees
    description: "Importing employee table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: id
        tests:
          - not_null 
          - unique   
  - name: stg_inventory_transaction_types
    description: "Importing inventory transaction types table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: id
        tests:
          - not_null 
          - unique   
  - name: stg_inventory_transactions
    description: "Importing inventory transactions table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: id
        tests:
          - not_null 
          - unique   
  - name: stg_invoices
    description: "Importing invoices table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: id
        tests:
          - not_null 
          - unique   
  - name: stg_order_details
    description: "Importing order details table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: id
        tests:
          - not_null 
          - unique   
  - name: stg_order_details_status
    description: "Importing order details status table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: id
        tests:
          - not_null 
          - unique   
  - name: stg_orders
    description: "Importing order table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: id
        tests:
          - not_null 
          - unique   
  - name: stg_orders_status
    description: "Importing order status table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: id
        tests:
          - not_null 
          - unique   
  - name: stg_orders_tax_status
    description: "Importing order tax status table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: id
        tests:
          - not_null 
          - unique   
  - name: stg_privileges
    description: "Importing privileges table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: id
        tests:
          - not_null 
          - unique   
  - name: stg_products
    description: "Importing products table from datalake to staging layer. Insertion of a timestamp, cleaning Pk to cast as integer and making sure PK as no duplicate"
    columns:
      - name: supplier_ids
        tests:
          - not_null 
          - unique   
  - name: stg_purchase_order_details
    description: "Importing purchase order details table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: id
        tests:
          - not_null 
          - unique   
  - name: stg_purchase_order_status
    description: "Importing purchase order status details table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: id
        tests:
          - not_null 
          - unique   
  - name: stg_purchase_orders
    description: "Importing purchase order table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: id
        tests:
          - not_null 
          - unique   
  - name: stg_sales_reports
    description: "Importing sales reports table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: CUSTOMER_ID
  - name: stg_shippers
    description: "Importing shippers table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: id
        tests:
          - not_null 
          - unique   
  - name: stg_strings
    description: "Importing strings table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: STRING_ID
        tests:
          - not_null 
          - unique   
  - name: stg_suppliers
    description: "Importing suppliers table from datalake to staging layer. Insertion of a timestamp and making sure PK as no duplicate"
    columns:
      - name: id
        tests:
          - not_null 
          - unique   


sources:
  - name: datalake
    database: "DL_NORTHWIND"
    schema: "DATA_LAKE"
    tables:
      - name: customer
      - name: date
      - name: employee_privileges
      - name: employees
      - name: inventory_transaction_types
      - name: inventory_transactions
      - name: invoices
      - name: order_details
      - name: order_details_status
      - name: orders
      - name: orders_status
      - name: orders_tax_status
      - name: privileges
      - name: products
      - name: purchase_order_details
      - name: purchase_order_status
      - name: purchase_orders
      - name: sales_reports
      - name: shippers
      - name: strings
      - name: suppliers
